// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flash.proto

package flash

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatisticCompound struct {
	GameSummary          *GameStatistic  `protobuf:"bytes,1,opt,name=game_summary,json=gameSummary,proto3" json:"game_summary,omitempty"`
	MapSummary           []*MapStatistic `protobuf:"bytes,2,rep,name=map_summary,json=mapSummary,proto3" json:"map_summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StatisticCompound) Reset()         { *m = StatisticCompound{} }
func (m *StatisticCompound) String() string { return proto.CompactTextString(m) }
func (*StatisticCompound) ProtoMessage()    {}
func (*StatisticCompound) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d8b97a8ce98af0, []int{0}
}

func (m *StatisticCompound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisticCompound.Unmarshal(m, b)
}
func (m *StatisticCompound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisticCompound.Marshal(b, m, deterministic)
}
func (m *StatisticCompound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisticCompound.Merge(m, src)
}
func (m *StatisticCompound) XXX_Size() int {
	return xxx_messageInfo_StatisticCompound.Size(m)
}
func (m *StatisticCompound) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisticCompound.DiscardUnknown(m)
}

var xxx_messageInfo_StatisticCompound proto.InternalMessageInfo

func (m *StatisticCompound) GetGameSummary() *GameStatistic {
	if m != nil {
		return m.GameSummary
	}
	return nil
}

func (m *StatisticCompound) GetMapSummary() []*MapStatistic {
	if m != nil {
		return m.MapSummary
	}
	return nil
}

type GameStatistic struct {
	Wins                 uint32   `protobuf:"varint,1,opt,name=wins,proto3" json:"wins,omitempty"`
	Deaths               uint32   `protobuf:"varint,2,opt,name=deaths,proto3" json:"deaths,omitempty"`
	GamesPlayed          uint32   `protobuf:"varint,3,opt,name=games_played,json=gamesPlayed,proto3" json:"games_played,omitempty"`
	InstantDeaths        uint32   `protobuf:"varint,4,opt,name=instant_deaths,json=instantDeaths,proto3" json:"instant_deaths,omitempty"`
	Checkpoints          uint32   `protobuf:"varint,5,opt,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameStatistic) Reset()         { *m = GameStatistic{} }
func (m *GameStatistic) String() string { return proto.CompactTextString(m) }
func (*GameStatistic) ProtoMessage()    {}
func (*GameStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d8b97a8ce98af0, []int{1}
}

func (m *GameStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameStatistic.Unmarshal(m, b)
}
func (m *GameStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameStatistic.Marshal(b, m, deterministic)
}
func (m *GameStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameStatistic.Merge(m, src)
}
func (m *GameStatistic) XXX_Size() int {
	return xxx_messageInfo_GameStatistic.Size(m)
}
func (m *GameStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_GameStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_GameStatistic proto.InternalMessageInfo

func (m *GameStatistic) GetWins() uint32 {
	if m != nil {
		return m.Wins
	}
	return 0
}

func (m *GameStatistic) GetDeaths() uint32 {
	if m != nil {
		return m.Deaths
	}
	return 0
}

func (m *GameStatistic) GetGamesPlayed() uint32 {
	if m != nil {
		return m.GamesPlayed
	}
	return 0
}

func (m *GameStatistic) GetInstantDeaths() uint32 {
	if m != nil {
		return m.InstantDeaths
	}
	return 0
}

func (m *GameStatistic) GetCheckpoints() uint32 {
	if m != nil {
		return m.Checkpoints
	}
	return 0
}

type MapStatistic struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TimeNeeded           uint64                 `protobuf:"varint,2,opt,name=time_needed,json=timeNeeded,proto3" json:"time_needed,omitempty"`
	RecordTime           uint64                 `protobuf:"varint,3,opt,name=record_time,json=recordTime,proto3" json:"record_time,omitempty"`
	Checkpoints          []*CheckpointStatistic `protobuf:"bytes,4,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MapStatistic) Reset()         { *m = MapStatistic{} }
func (m *MapStatistic) String() string { return proto.CompactTextString(m) }
func (*MapStatistic) ProtoMessage()    {}
func (*MapStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d8b97a8ce98af0, []int{2}
}

func (m *MapStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapStatistic.Unmarshal(m, b)
}
func (m *MapStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapStatistic.Marshal(b, m, deterministic)
}
func (m *MapStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapStatistic.Merge(m, src)
}
func (m *MapStatistic) XXX_Size() int {
	return xxx_messageInfo_MapStatistic.Size(m)
}
func (m *MapStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_MapStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_MapStatistic proto.InternalMessageInfo

func (m *MapStatistic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MapStatistic) GetTimeNeeded() uint64 {
	if m != nil {
		return m.TimeNeeded
	}
	return 0
}

func (m *MapStatistic) GetRecordTime() uint64 {
	if m != nil {
		return m.RecordTime
	}
	return 0
}

func (m *MapStatistic) GetCheckpoints() []*CheckpointStatistic {
	if m != nil {
		return m.Checkpoints
	}
	return nil
}

type CheckpointStatistic struct {
	Checkpoint           int32    `protobuf:"fixed32,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	TimeNeeded           uint64   `protobuf:"varint,2,opt,name=time_needed,json=timeNeeded,proto3" json:"time_needed,omitempty"`
	RecordTime           uint64   `protobuf:"varint,3,opt,name=record_time,json=recordTime,proto3" json:"record_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckpointStatistic) Reset()         { *m = CheckpointStatistic{} }
func (m *CheckpointStatistic) String() string { return proto.CompactTextString(m) }
func (*CheckpointStatistic) ProtoMessage()    {}
func (*CheckpointStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d8b97a8ce98af0, []int{3}
}

func (m *CheckpointStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckpointStatistic.Unmarshal(m, b)
}
func (m *CheckpointStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckpointStatistic.Marshal(b, m, deterministic)
}
func (m *CheckpointStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckpointStatistic.Merge(m, src)
}
func (m *CheckpointStatistic) XXX_Size() int {
	return xxx_messageInfo_CheckpointStatistic.Size(m)
}
func (m *CheckpointStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckpointStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_CheckpointStatistic proto.InternalMessageInfo

func (m *CheckpointStatistic) GetCheckpoint() int32 {
	if m != nil {
		return m.Checkpoint
	}
	return 0
}

func (m *CheckpointStatistic) GetTimeNeeded() uint64 {
	if m != nil {
		return m.TimeNeeded
	}
	return 0
}

func (m *CheckpointStatistic) GetRecordTime() uint64 {
	if m != nil {
		return m.RecordTime
	}
	return 0
}

func init() {
	proto.RegisterType((*StatisticCompound)(nil), "StatisticCompound")
	proto.RegisterType((*GameStatistic)(nil), "GameStatistic")
	proto.RegisterType((*MapStatistic)(nil), "MapStatistic")
	proto.RegisterType((*CheckpointStatistic)(nil), "CheckpointStatistic")
}

func init() { proto.RegisterFile("flash.proto", fileDescriptor_83d8b97a8ce98af0) }

var fileDescriptor_83d8b97a8ce98af0 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x80, 0xe9, 0x56, 0x07, 0xbe, 0xac, 0x13, 0xa3, 0x48, 0x4f, 0x3a, 0x07, 0xc2, 0x4e, 0x05,
	0x27, 0xf8, 0x07, 0x26, 0x78, 0x52, 0xa4, 0xf3, 0x5e, 0x9e, 0xed, 0xd3, 0x05, 0x97, 0x34, 0x34,
	0x99, 0x63, 0xff, 0xc5, 0xbb, 0x7f, 0x53, 0xfa, 0x5a, 0xb6, 0x0e, 0xbc, 0x79, 0x4b, 0xbf, 0x7e,
	0x79, 0xfd, 0x1a, 0x02, 0xe2, 0x7d, 0x85, 0x6e, 0x99, 0xd8, 0xaa, 0xf4, 0xe5, 0xe4, 0x0b, 0x4e,
	0x17, 0x1e, 0xbd, 0x72, 0x5e, 0xe5, 0xf3, 0x52, 0xdb, 0x72, 0x6d, 0x0a, 0x79, 0x0b, 0xc3, 0x0f,
	0xd4, 0x94, 0xb9, 0xb5, 0xd6, 0x58, 0x6d, 0xe3, 0x60, 0x1c, 0x4c, 0xc5, 0x6c, 0x94, 0x3c, 0xa2,
	0xa6, 0x9d, 0x9d, 0x8a, 0xda, 0x59, 0x34, 0x8a, 0x4c, 0x40, 0x68, 0xb4, 0xbb, 0x1d, 0xbd, 0x71,
	0x7f, 0x2a, 0x66, 0x51, 0xf2, 0x84, 0x76, 0xbf, 0x01, 0x34, 0xda, 0xd6, 0x9f, 0xfc, 0x04, 0x10,
	0x1d, 0x8c, 0x93, 0x12, 0xc2, 0x8d, 0x32, 0x8e, 0x3f, 0x16, 0xa5, 0xbc, 0x96, 0x17, 0x30, 0x28,
	0x08, 0xfd, 0xd2, 0xc5, 0x3d, 0xa6, 0xed, 0x93, 0xbc, 0x6e, 0x02, 0x5d, 0x66, 0x57, 0xb8, 0xa5,
	0x22, 0xee, 0xf3, 0x5b, 0x0e, 0x72, 0x2f, 0x8c, 0xe4, 0x0d, 0x8c, 0x94, 0x71, 0x1e, 0x8d, 0xcf,
	0xda, 0x11, 0x21, 0x4b, 0x51, 0x4b, 0x1f, 0x9a, 0x49, 0x63, 0x10, 0xf9, 0x92, 0xf2, 0x4f, 0x5b,
	0x2a, 0xe3, 0x5d, 0x7c, 0xd4, 0x0c, 0xea, 0xa0, 0xc9, 0x77, 0x00, 0xc3, 0xee, 0x6f, 0xd4, 0xa1,
	0x06, 0x35, 0x71, 0xe8, 0x71, 0xca, 0x6b, 0x79, 0x05, 0xc2, 0x2b, 0x4d, 0x99, 0x21, 0x2a, 0xa8,
	0xe0, 0xda, 0x30, 0x85, 0x1a, 0x3d, 0x33, 0xa9, 0x85, 0x8a, 0xf2, 0xb2, 0x2a, 0xb2, 0x1a, 0x72,
	0x70, 0x98, 0x42, 0x83, 0x5e, 0x95, 0x26, 0x79, 0x7f, 0x18, 0x12, 0xf2, 0x01, 0x9e, 0x27, 0xf3,
	0x1d, 0xeb, 0x1c, 0x7c, 0x37, 0x6f, 0x03, 0x67, 0x7f, 0x38, 0xf2, 0x12, 0x60, 0x6f, 0x71, 0xea,
	0x49, 0xda, 0x21, 0xff, 0x0f, 0x7e, 0x1b, 0xf0, 0x05, 0xba, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x71, 0x95, 0xd4, 0x71, 0x4f, 0x02, 0x00, 0x00,
}
