// Code generated by MockGen. DO NOT EDIT.
// Source: freggy.dev/stats/service/v1 (interfaces: StatsServiceServer)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	v1 "freggy.dev/stats/service/v1"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStatsServiceServer is a mock of StatsServiceServer interface
type MockStatsServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockStatsServiceServerMockRecorder
}

// MockStatsServiceServerMockRecorder is the mock recorder for MockStatsServiceServer
type MockStatsServiceServerMockRecorder struct {
	mock *MockStatsServiceServer
}

// NewMockStatsServiceServer creates a new mock instance
func NewMockStatsServiceServer(ctrl *gomock.Controller) *MockStatsServiceServer {
	mock := &MockStatsServiceServer{ctrl: ctrl}
	mock.recorder = &MockStatsServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStatsServiceServer) EXPECT() *MockStatsServiceServerMockRecorder {
	return m.recorder
}

// GetFlashMapHighscoreForPlayer mocks base method
func (m *MockStatsServiceServer) GetFlashMapHighscoreForPlayer(arg0 context.Context, arg1 *v1.GetFlashMapHighscoreForPlayerRequest) (*v1.GetFlashMapHighscoreForPlayerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlashMapHighscoreForPlayer", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetFlashMapHighscoreForPlayerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlashMapHighscoreForPlayer indicates an expected call of GetFlashMapHighscoreForPlayer
func (mr *MockStatsServiceServerMockRecorder) GetFlashMapHighscoreForPlayer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlashMapHighscoreForPlayer", reflect.TypeOf((*MockStatsServiceServer)(nil).GetFlashMapHighscoreForPlayer), arg0, arg1)
}

// GetGlobalFlashMapHighscore mocks base method
func (m *MockStatsServiceServer) GetGlobalFlashMapHighscore(arg0 context.Context, arg1 *v1.GetGlobalFlashMapHighscoreRequest) (*v1.GetGlobalFlashMapHighscoreResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalFlashMapHighscore", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetGlobalFlashMapHighscoreResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalFlashMapHighscore indicates an expected call of GetGlobalFlashMapHighscore
func (mr *MockStatsServiceServerMockRecorder) GetGlobalFlashMapHighscore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalFlashMapHighscore", reflect.TypeOf((*MockStatsServiceServer)(nil).GetGlobalFlashMapHighscore), arg0, arg1)
}

// GetTopFlashMapHighscores mocks base method
func (m *MockStatsServiceServer) GetTopFlashMapHighscores(arg0 context.Context, arg1 *v1.GetTopFlashMapHighscoresRequest) (*v1.GetTopFlashMapHighscoresResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopFlashMapHighscores", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetTopFlashMapHighscoresResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopFlashMapHighscores indicates an expected call of GetTopFlashMapHighscores
func (mr *MockStatsServiceServerMockRecorder) GetTopFlashMapHighscores(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopFlashMapHighscores", reflect.TypeOf((*MockStatsServiceServer)(nil).GetTopFlashMapHighscores), arg0, arg1)
}

// GetTopFlashPlayersByPoints mocks base method
func (m *MockStatsServiceServer) GetTopFlashPlayersByPoints(arg0 context.Context, arg1 *v1.GetTopPlayersByPointsRequest) (*v1.GetTopPlayersByPointsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopFlashPlayersByPoints", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetTopPlayersByPointsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopFlashPlayersByPoints indicates an expected call of GetTopFlashPlayersByPoints
func (mr *MockStatsServiceServerMockRecorder) GetTopFlashPlayersByPoints(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopFlashPlayersByPoints", reflect.TypeOf((*MockStatsServiceServer)(nil).GetTopFlashPlayersByPoints), arg0, arg1)
}

// UpdateFlashStatistics mocks base method
func (m *MockStatsServiceServer) UpdateFlashStatistics(arg0 context.Context, arg1 *v1.UpdateFlashStatisticsRequests) (*v1.UpdateFlashStatisticsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFlashStatistics", arg0, arg1)
	ret0, _ := ret[0].(*v1.UpdateFlashStatisticsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFlashStatistics indicates an expected call of UpdateFlashStatistics
func (mr *MockStatsServiceServerMockRecorder) UpdateFlashStatistics(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFlashStatistics", reflect.TypeOf((*MockStatsServiceServer)(nil).UpdateFlashStatistics), arg0, arg1)
}
