// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package dev.freggy.stats.service;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FlashMapStatsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FlashMapStatsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string playerId = 1;</code>
     */
    java.lang.String getPlayerId();
    /**
     * <code>string playerId = 1;</code>
     */
    com.google.protobuf.ByteString
        getPlayerIdBytes();

    /**
     * <code>repeated string maps = 2;</code>
     */
    java.util.List<java.lang.String>
        getMapsList();
    /**
     * <code>repeated string maps = 2;</code>
     */
    int getMapsCount();
    /**
     * <code>repeated string maps = 2;</code>
     */
    java.lang.String getMaps(int index);
    /**
     * <code>repeated string maps = 2;</code>
     */
    com.google.protobuf.ByteString
        getMapsBytes(int index);
  }
  /**
   * Protobuf type {@code FlashMapStatsRequest}
   */
  public  static final class FlashMapStatsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FlashMapStatsRequest)
      FlashMapStatsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FlashMapStatsRequest.newBuilder() to construct.
    private FlashMapStatsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FlashMapStatsRequest() {
      playerId_ = "";
      maps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FlashMapStatsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              playerId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                maps_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              maps_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          maps_ = maps_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.freggy.stats.service.Service.internal_static_FlashMapStatsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.freggy.stats.service.Service.internal_static_FlashMapStatsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.freggy.stats.service.Service.FlashMapStatsRequest.class, dev.freggy.stats.service.Service.FlashMapStatsRequest.Builder.class);
    }

    private int bitField0_;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object playerId_;
    /**
     * <code>string playerId = 1;</code>
     */
    public java.lang.String getPlayerId() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerId_ = s;
        return s;
      }
    }
    /**
     * <code>string playerId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAPS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList maps_;
    /**
     * <code>repeated string maps = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMapsList() {
      return maps_;
    }
    /**
     * <code>repeated string maps = 2;</code>
     */
    public int getMapsCount() {
      return maps_.size();
    }
    /**
     * <code>repeated string maps = 2;</code>
     */
    public java.lang.String getMaps(int index) {
      return maps_.get(index);
    }
    /**
     * <code>repeated string maps = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMapsBytes(int index) {
      return maps_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPlayerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, playerId_);
      }
      for (int i = 0; i < maps_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, maps_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPlayerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, playerId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < maps_.size(); i++) {
          dataSize += computeStringSizeNoTag(maps_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMapsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.freggy.stats.service.Service.FlashMapStatsRequest)) {
        return super.equals(obj);
      }
      dev.freggy.stats.service.Service.FlashMapStatsRequest other = (dev.freggy.stats.service.Service.FlashMapStatsRequest) obj;

      boolean result = true;
      result = result && getPlayerId()
          .equals(other.getPlayerId());
      result = result && getMapsList()
          .equals(other.getMapsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId().hashCode();
      if (getMapsCount() > 0) {
        hash = (37 * hash) + MAPS_FIELD_NUMBER;
        hash = (53 * hash) + getMapsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.freggy.stats.service.Service.FlashMapStatsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.freggy.stats.service.Service.FlashMapStatsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashMapStatsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.freggy.stats.service.Service.FlashMapStatsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashMapStatsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.freggy.stats.service.Service.FlashMapStatsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashMapStatsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.freggy.stats.service.Service.FlashMapStatsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashMapStatsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.freggy.stats.service.Service.FlashMapStatsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashMapStatsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.freggy.stats.service.Service.FlashMapStatsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.freggy.stats.service.Service.FlashMapStatsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FlashMapStatsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FlashMapStatsRequest)
        dev.freggy.stats.service.Service.FlashMapStatsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.freggy.stats.service.Service.internal_static_FlashMapStatsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.freggy.stats.service.Service.internal_static_FlashMapStatsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.freggy.stats.service.Service.FlashMapStatsRequest.class, dev.freggy.stats.service.Service.FlashMapStatsRequest.Builder.class);
      }

      // Construct using dev.freggy.stats.service.Service.FlashMapStatsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        playerId_ = "";

        maps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.freggy.stats.service.Service.internal_static_FlashMapStatsRequest_descriptor;
      }

      @java.lang.Override
      public dev.freggy.stats.service.Service.FlashMapStatsRequest getDefaultInstanceForType() {
        return dev.freggy.stats.service.Service.FlashMapStatsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public dev.freggy.stats.service.Service.FlashMapStatsRequest build() {
        dev.freggy.stats.service.Service.FlashMapStatsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.freggy.stats.service.Service.FlashMapStatsRequest buildPartial() {
        dev.freggy.stats.service.Service.FlashMapStatsRequest result = new dev.freggy.stats.service.Service.FlashMapStatsRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.playerId_ = playerId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          maps_ = maps_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.maps_ = maps_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.freggy.stats.service.Service.FlashMapStatsRequest) {
          return mergeFrom((dev.freggy.stats.service.Service.FlashMapStatsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.freggy.stats.service.Service.FlashMapStatsRequest other) {
        if (other == dev.freggy.stats.service.Service.FlashMapStatsRequest.getDefaultInstance()) return this;
        if (!other.getPlayerId().isEmpty()) {
          playerId_ = other.playerId_;
          onChanged();
        }
        if (!other.maps_.isEmpty()) {
          if (maps_.isEmpty()) {
            maps_ = other.maps_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMapsIsMutable();
            maps_.addAll(other.maps_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dev.freggy.stats.service.Service.FlashMapStatsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dev.freggy.stats.service.Service.FlashMapStatsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object playerId_ = "";
      /**
       * <code>string playerId = 1;</code>
       */
      public java.lang.String getPlayerId() {
        java.lang.Object ref = playerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        java.lang.Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public Builder setPlayerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = getDefaultInstance().getPlayerId();
        onChanged();
        return this;
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public Builder setPlayerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList maps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMapsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          maps_ = new com.google.protobuf.LazyStringArrayList(maps_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMapsList() {
        return maps_.getUnmodifiableView();
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public int getMapsCount() {
        return maps_.size();
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public java.lang.String getMaps(int index) {
        return maps_.get(index);
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMapsBytes(int index) {
        return maps_.getByteString(index);
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public Builder setMaps(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMapsIsMutable();
        maps_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public Builder addMaps(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMapsIsMutable();
        maps_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public Builder addAllMaps(
          java.lang.Iterable<java.lang.String> values) {
        ensureMapsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, maps_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public Builder clearMaps() {
        maps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public Builder addMapsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMapsIsMutable();
        maps_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FlashMapStatsRequest)
    }

    // @@protoc_insertion_point(class_scope:FlashMapStatsRequest)
    private static final dev.freggy.stats.service.Service.FlashMapStatsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.freggy.stats.service.Service.FlashMapStatsRequest();
    }

    public static dev.freggy.stats.service.Service.FlashMapStatsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FlashMapStatsRequest>
        PARSER = new com.google.protobuf.AbstractParser<FlashMapStatsRequest>() {
      @java.lang.Override
      public FlashMapStatsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FlashMapStatsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FlashMapStatsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FlashMapStatsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.freggy.stats.service.Service.FlashMapStatsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FlashGameStatsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FlashGameStatsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string playerId = 1;</code>
     */
    java.lang.String getPlayerId();
    /**
     * <code>string playerId = 1;</code>
     */
    com.google.protobuf.ByteString
        getPlayerIdBytes();
  }
  /**
   * Protobuf type {@code FlashGameStatsRequest}
   */
  public  static final class FlashGameStatsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FlashGameStatsRequest)
      FlashGameStatsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FlashGameStatsRequest.newBuilder() to construct.
    private FlashGameStatsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FlashGameStatsRequest() {
      playerId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FlashGameStatsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              playerId_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.freggy.stats.service.Service.internal_static_FlashGameStatsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.freggy.stats.service.Service.internal_static_FlashGameStatsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.freggy.stats.service.Service.FlashGameStatsRequest.class, dev.freggy.stats.service.Service.FlashGameStatsRequest.Builder.class);
    }

    public static final int PLAYERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object playerId_;
    /**
     * <code>string playerId = 1;</code>
     */
    public java.lang.String getPlayerId() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerId_ = s;
        return s;
      }
    }
    /**
     * <code>string playerId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPlayerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, playerId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPlayerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, playerId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.freggy.stats.service.Service.FlashGameStatsRequest)) {
        return super.equals(obj);
      }
      dev.freggy.stats.service.Service.FlashGameStatsRequest other = (dev.freggy.stats.service.Service.FlashGameStatsRequest) obj;

      boolean result = true;
      result = result && getPlayerId()
          .equals(other.getPlayerId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.freggy.stats.service.Service.FlashGameStatsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.freggy.stats.service.Service.FlashGameStatsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashGameStatsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.freggy.stats.service.Service.FlashGameStatsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashGameStatsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.freggy.stats.service.Service.FlashGameStatsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashGameStatsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.freggy.stats.service.Service.FlashGameStatsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashGameStatsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.freggy.stats.service.Service.FlashGameStatsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashGameStatsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.freggy.stats.service.Service.FlashGameStatsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.freggy.stats.service.Service.FlashGameStatsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FlashGameStatsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FlashGameStatsRequest)
        dev.freggy.stats.service.Service.FlashGameStatsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.freggy.stats.service.Service.internal_static_FlashGameStatsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.freggy.stats.service.Service.internal_static_FlashGameStatsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.freggy.stats.service.Service.FlashGameStatsRequest.class, dev.freggy.stats.service.Service.FlashGameStatsRequest.Builder.class);
      }

      // Construct using dev.freggy.stats.service.Service.FlashGameStatsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        playerId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.freggy.stats.service.Service.internal_static_FlashGameStatsRequest_descriptor;
      }

      @java.lang.Override
      public dev.freggy.stats.service.Service.FlashGameStatsRequest getDefaultInstanceForType() {
        return dev.freggy.stats.service.Service.FlashGameStatsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public dev.freggy.stats.service.Service.FlashGameStatsRequest build() {
        dev.freggy.stats.service.Service.FlashGameStatsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.freggy.stats.service.Service.FlashGameStatsRequest buildPartial() {
        dev.freggy.stats.service.Service.FlashGameStatsRequest result = new dev.freggy.stats.service.Service.FlashGameStatsRequest(this);
        result.playerId_ = playerId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.freggy.stats.service.Service.FlashGameStatsRequest) {
          return mergeFrom((dev.freggy.stats.service.Service.FlashGameStatsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.freggy.stats.service.Service.FlashGameStatsRequest other) {
        if (other == dev.freggy.stats.service.Service.FlashGameStatsRequest.getDefaultInstance()) return this;
        if (!other.getPlayerId().isEmpty()) {
          playerId_ = other.playerId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dev.freggy.stats.service.Service.FlashGameStatsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dev.freggy.stats.service.Service.FlashGameStatsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object playerId_ = "";
      /**
       * <code>string playerId = 1;</code>
       */
      public java.lang.String getPlayerId() {
        java.lang.Object ref = playerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        java.lang.Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public Builder setPlayerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = getDefaultInstance().getPlayerId();
        onChanged();
        return this;
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public Builder setPlayerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FlashGameStatsRequest)
    }

    // @@protoc_insertion_point(class_scope:FlashGameStatsRequest)
    private static final dev.freggy.stats.service.Service.FlashGameStatsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.freggy.stats.service.Service.FlashGameStatsRequest();
    }

    public static dev.freggy.stats.service.Service.FlashGameStatsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FlashGameStatsRequest>
        PARSER = new com.google.protobuf.AbstractParser<FlashGameStatsRequest>() {
      @java.lang.Override
      public FlashGameStatsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FlashGameStatsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FlashGameStatsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FlashGameStatsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.freggy.stats.service.Service.FlashGameStatsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FlashStatsCompoundRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FlashStatsCompoundRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string playerId = 1;</code>
     */
    java.lang.String getPlayerId();
    /**
     * <code>string playerId = 1;</code>
     */
    com.google.protobuf.ByteString
        getPlayerIdBytes();

    /**
     * <code>repeated string maps = 2;</code>
     */
    java.util.List<java.lang.String>
        getMapsList();
    /**
     * <code>repeated string maps = 2;</code>
     */
    int getMapsCount();
    /**
     * <code>repeated string maps = 2;</code>
     */
    java.lang.String getMaps(int index);
    /**
     * <code>repeated string maps = 2;</code>
     */
    com.google.protobuf.ByteString
        getMapsBytes(int index);
  }
  /**
   * Protobuf type {@code FlashStatsCompoundRequest}
   */
  public  static final class FlashStatsCompoundRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FlashStatsCompoundRequest)
      FlashStatsCompoundRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FlashStatsCompoundRequest.newBuilder() to construct.
    private FlashStatsCompoundRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FlashStatsCompoundRequest() {
      playerId_ = "";
      maps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FlashStatsCompoundRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              playerId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                maps_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              maps_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          maps_ = maps_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.freggy.stats.service.Service.internal_static_FlashStatsCompoundRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.freggy.stats.service.Service.internal_static_FlashStatsCompoundRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.freggy.stats.service.Service.FlashStatsCompoundRequest.class, dev.freggy.stats.service.Service.FlashStatsCompoundRequest.Builder.class);
    }

    private int bitField0_;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object playerId_;
    /**
     * <code>string playerId = 1;</code>
     */
    public java.lang.String getPlayerId() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerId_ = s;
        return s;
      }
    }
    /**
     * <code>string playerId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAPS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList maps_;
    /**
     * <code>repeated string maps = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMapsList() {
      return maps_;
    }
    /**
     * <code>repeated string maps = 2;</code>
     */
    public int getMapsCount() {
      return maps_.size();
    }
    /**
     * <code>repeated string maps = 2;</code>
     */
    public java.lang.String getMaps(int index) {
      return maps_.get(index);
    }
    /**
     * <code>repeated string maps = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMapsBytes(int index) {
      return maps_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPlayerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, playerId_);
      }
      for (int i = 0; i < maps_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, maps_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPlayerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, playerId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < maps_.size(); i++) {
          dataSize += computeStringSizeNoTag(maps_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMapsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.freggy.stats.service.Service.FlashStatsCompoundRequest)) {
        return super.equals(obj);
      }
      dev.freggy.stats.service.Service.FlashStatsCompoundRequest other = (dev.freggy.stats.service.Service.FlashStatsCompoundRequest) obj;

      boolean result = true;
      result = result && getPlayerId()
          .equals(other.getPlayerId());
      result = result && getMapsList()
          .equals(other.getMapsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId().hashCode();
      if (getMapsCount() > 0) {
        hash = (37 * hash) + MAPS_FIELD_NUMBER;
        hash = (53 * hash) + getMapsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.freggy.stats.service.Service.FlashStatsCompoundRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.freggy.stats.service.Service.FlashStatsCompoundRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashStatsCompoundRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.freggy.stats.service.Service.FlashStatsCompoundRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashStatsCompoundRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.freggy.stats.service.Service.FlashStatsCompoundRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashStatsCompoundRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.freggy.stats.service.Service.FlashStatsCompoundRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashStatsCompoundRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dev.freggy.stats.service.Service.FlashStatsCompoundRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.freggy.stats.service.Service.FlashStatsCompoundRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.freggy.stats.service.Service.FlashStatsCompoundRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.freggy.stats.service.Service.FlashStatsCompoundRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FlashStatsCompoundRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FlashStatsCompoundRequest)
        dev.freggy.stats.service.Service.FlashStatsCompoundRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.freggy.stats.service.Service.internal_static_FlashStatsCompoundRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.freggy.stats.service.Service.internal_static_FlashStatsCompoundRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.freggy.stats.service.Service.FlashStatsCompoundRequest.class, dev.freggy.stats.service.Service.FlashStatsCompoundRequest.Builder.class);
      }

      // Construct using dev.freggy.stats.service.Service.FlashStatsCompoundRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        playerId_ = "";

        maps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.freggy.stats.service.Service.internal_static_FlashStatsCompoundRequest_descriptor;
      }

      @java.lang.Override
      public dev.freggy.stats.service.Service.FlashStatsCompoundRequest getDefaultInstanceForType() {
        return dev.freggy.stats.service.Service.FlashStatsCompoundRequest.getDefaultInstance();
      }

      @java.lang.Override
      public dev.freggy.stats.service.Service.FlashStatsCompoundRequest build() {
        dev.freggy.stats.service.Service.FlashStatsCompoundRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.freggy.stats.service.Service.FlashStatsCompoundRequest buildPartial() {
        dev.freggy.stats.service.Service.FlashStatsCompoundRequest result = new dev.freggy.stats.service.Service.FlashStatsCompoundRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.playerId_ = playerId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          maps_ = maps_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.maps_ = maps_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.freggy.stats.service.Service.FlashStatsCompoundRequest) {
          return mergeFrom((dev.freggy.stats.service.Service.FlashStatsCompoundRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.freggy.stats.service.Service.FlashStatsCompoundRequest other) {
        if (other == dev.freggy.stats.service.Service.FlashStatsCompoundRequest.getDefaultInstance()) return this;
        if (!other.getPlayerId().isEmpty()) {
          playerId_ = other.playerId_;
          onChanged();
        }
        if (!other.maps_.isEmpty()) {
          if (maps_.isEmpty()) {
            maps_ = other.maps_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMapsIsMutable();
            maps_.addAll(other.maps_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dev.freggy.stats.service.Service.FlashStatsCompoundRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dev.freggy.stats.service.Service.FlashStatsCompoundRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object playerId_ = "";
      /**
       * <code>string playerId = 1;</code>
       */
      public java.lang.String getPlayerId() {
        java.lang.Object ref = playerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        java.lang.Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public Builder setPlayerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = getDefaultInstance().getPlayerId();
        onChanged();
        return this;
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public Builder setPlayerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList maps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMapsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          maps_ = new com.google.protobuf.LazyStringArrayList(maps_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMapsList() {
        return maps_.getUnmodifiableView();
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public int getMapsCount() {
        return maps_.size();
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public java.lang.String getMaps(int index) {
        return maps_.get(index);
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMapsBytes(int index) {
        return maps_.getByteString(index);
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public Builder setMaps(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMapsIsMutable();
        maps_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public Builder addMaps(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMapsIsMutable();
        maps_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public Builder addAllMaps(
          java.lang.Iterable<java.lang.String> values) {
        ensureMapsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, maps_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public Builder clearMaps() {
        maps_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string maps = 2;</code>
       */
      public Builder addMapsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMapsIsMutable();
        maps_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FlashStatsCompoundRequest)
    }

    // @@protoc_insertion_point(class_scope:FlashStatsCompoundRequest)
    private static final dev.freggy.stats.service.Service.FlashStatsCompoundRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.freggy.stats.service.Service.FlashStatsCompoundRequest();
    }

    public static dev.freggy.stats.service.Service.FlashStatsCompoundRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FlashStatsCompoundRequest>
        PARSER = new com.google.protobuf.AbstractParser<FlashStatsCompoundRequest>() {
      @java.lang.Override
      public FlashStatsCompoundRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FlashStatsCompoundRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FlashStatsCompoundRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FlashStatsCompoundRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.freggy.stats.service.Service.FlashStatsCompoundRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FlashMapStatsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FlashMapStatsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FlashGameStatsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FlashGameStatsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FlashStatsCompoundRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FlashStatsCompoundRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\032\013flash.proto\"6\n\024FlashMap" +
      "StatsRequest\022\020\n\010playerId\030\001 \001(\t\022\014\n\004maps\030\002" +
      " \003(\t\")\n\025FlashGameStatsRequest\022\020\n\010playerI" +
      "d\030\001 \001(\t\";\n\031FlashStatsCompoundRequest\022\020\n\010" +
      "playerId\030\001 \001(\t\022\014\n\004maps\030\002 \003(\t2\336\001\n\014StatsSe" +
      "rvice\022B\n\020GetFlashMapStats\022\025.FlashMapStat" +
      "sRequest\032\027.FlashStatisticCompound\022D\n\021Get" +
      "FlashGameStats\022\026.FlashGameStatsRequest\032\027" +
      ".FlashStatisticCompound\022D\n\rGetFlashStats" +
      "\022\032.FlashStatsCompoundRequest\032\027.FlashStat" +
      "isticCompoundB#\n\030dev.freggy.stats.servic" +
      "eZ\007serviceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          dev.freggy.stats.model.Flash.getDescriptor(),
        }, assigner);
    internal_static_FlashMapStatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FlashMapStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FlashMapStatsRequest_descriptor,
        new java.lang.String[] { "PlayerId", "Maps", });
    internal_static_FlashGameStatsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FlashGameStatsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FlashGameStatsRequest_descriptor,
        new java.lang.String[] { "PlayerId", });
    internal_static_FlashStatsCompoundRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FlashStatsCompoundRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FlashStatsCompoundRequest_descriptor,
        new java.lang.String[] { "PlayerId", "Maps", });
    dev.freggy.stats.model.Flash.getDescriptor();
  }

  @javax.ws.rs.ext.Provider
  @javax.ws.rs.Produces({"application/protobuf", "application/json"})
  @javax.ws.rs.Consumes({"application/protobuf", "application/json"})
  public static class ProtoBufMessageProvider implements javax.ws.rs.ext.MessageBodyWriter<com.google.protobuf.Message>, javax.ws.rs.ext.MessageBodyReader<com.google.protobuf.Message> {
  
          @Override
          public boolean isWriteable(Class<?> type, java.lang.reflect.Type genericType, java.lang.annotation.Annotation[] annotations, javax.ws.rs.core.MediaType mediaType) {
              return com.google.protobuf.Message.class.isAssignableFrom(type) && ("json".equals(mediaType.getSubtype()) || "protobuf".equals(mediaType.getSubtype()));
          }
  
          @Override
          public long getSize(com.google.protobuf.Message t, Class<?> type, java.lang.reflect.Type genericType, java.lang.annotation.Annotation[] annotations, javax.ws.rs.core.MediaType mediaType) {
              if (t == null) {
                  return -1;
              }
              java.io.ByteArrayOutputStream out = new java.io.ByteArrayOutputStream();
              try {
                  writeTo(t, type, genericType, annotations, mediaType, null, out);
              } catch (java.io.IOException e) {
                  return -1;
              }
              return out.size();
          }
  
          @Override
          public void writeTo(com.google.protobuf.Message t, Class<?> type, java.lang.reflect.Type genericType, java.lang.annotation.Annotation[] annotations, javax.ws.rs.core.MediaType mediaType, javax.ws.rs.core.MultivaluedMap<String, Object> httpHeaders, java.io.OutputStream entityStream) throws java.io.IOException, javax.ws.rs.WebApplicationException {
              switch (mediaType.getSubtype()) {
                  case "protobuf":
                      t.writeTo(entityStream);
                      break;
                  case "json":
                      entityStream.write(com.google.protobuf.util.JsonFormat.printer().print(t).getBytes("UTF-8"));
                      break;
                  default:
                      throw new javax.ws.rs.WebApplicationException("MediaType not supported!");
              }
  
          }
  
          @Override
          public boolean isReadable(Class<?> type, java.lang.reflect.Type genericType, java.lang.annotation.Annotation[] annotations, javax.ws.rs.core.MediaType mediaType) {
              return com.google.protobuf.Message.class.isAssignableFrom(type) && ("json".equals(mediaType.getSubtype()) || "protobuf".equals(mediaType.getSubtype()));
          }
  
          @Override
          public com.google.protobuf.Message readFrom(Class<com.google.protobuf.Message> type, java.lang.reflect.Type genericType, java.lang.annotation.Annotation[] annotations, javax.ws.rs.core.MediaType mediaType, javax.ws.rs.core.MultivaluedMap<String, String> httpHeaders, java.io.InputStream entityStream) throws java.io.IOException, javax.ws.rs.WebApplicationException {
              try {
                  switch (mediaType.getSubtype()) {
                      case "protobuf":
                          java.lang.reflect.Method m = type.getMethod("parseFrom", java.io.InputStream.class);
                          return (com.google.protobuf.Message) m.invoke(null, entityStream);
                      case "json":
                          com.google.protobuf.Message.Builder msg = (com.google.protobuf.Message.Builder)type.getMethod("newBuilder").invoke(null);
                          com.google.protobuf.util.JsonFormat.parser().merge(new java.io.InputStreamReader(entityStream), msg);
                          return msg.build();
                      default:
                          throw new javax.ws.rs.WebApplicationException("MediaType not supported!");
                  }
              } catch (Exception e) {
                  throw new javax.ws.rs.WebApplicationException(e);
              }
          }
  }
  
  @javax.ws.rs.Path( "/StatsService" )
  public interface StatsService {
    @javax.ws.rs.POST
    @javax.ws.rs.Path( "/GetFlashMapStats" )
    @javax.ws.rs.Consumes({"application/protobuf", "application/json"})
    @javax.ws.rs.Produces({"application/protobuf", "application/json"})
    dev.freggy.stats.service.Service.FlashStatisticCompound getFlashMapStats(dev.freggy.stats.service.Service.FlashMapStatsRequest request);
    @javax.ws.rs.POST
    @javax.ws.rs.Path( "/GetFlashGameStats" )
    @javax.ws.rs.Consumes({"application/protobuf", "application/json"})
    @javax.ws.rs.Produces({"application/protobuf", "application/json"})
    dev.freggy.stats.service.Service.FlashStatisticCompound getFlashGameStats(dev.freggy.stats.service.Service.FlashGameStatsRequest request);
    @javax.ws.rs.POST
    @javax.ws.rs.Path( "/GetFlashStats" )
    @javax.ws.rs.Consumes({"application/protobuf", "application/json"})
    @javax.ws.rs.Produces({"application/protobuf", "application/json"})
    dev.freggy.stats.service.Service.FlashStatisticCompound getFlashStats(dev.freggy.stats.service.Service.FlashStatsCompoundRequest request);
  }
  
  public static class StatsServiceClient implements dev.freggy.stats.service.Service.StatsService {
    private final javax.ws.rs.client.WebTarget target;
  
    public StatsServiceClient(javax.ws.rs.client.WebTarget target) {
      this.target = target.path("StatsService");
      this.target.register(new dev.freggy.stats.service.Service.ProtoBufMessageProvider());
    }
  
    private <R> R call(String path, com.google.protobuf.Message req, Class<R> responseClass) {
      javax.ws.rs.core.Response response = target.path(path)
          .request("application/protobuf")
          .post(javax.ws.rs.client.Entity.entity(req, "application/protobuf"));
  	 if (response.getStatusInfo().getFamily() == javax.ws.rs.core.Response.Status.Family.SUCCESSFUL) {
          R r = response.readEntity(responseClass);
          response.close();
          return r;
      } else {
          throw new javax.ws.rs.WebApplicationException(response);
      }
    }
  
  
    @Override
    public dev.freggy.stats.service.Service.FlashStatisticCompound getFlashMapStats(dev.freggy.stats.service.Service.FlashMapStatsRequest request) {
      return call("/GetFlashMapStats", request, dev.freggy.stats.service.Service.FlashStatisticCompound.class);
    }
  
    @Override
    public dev.freggy.stats.service.Service.FlashStatisticCompound getFlashGameStats(dev.freggy.stats.service.Service.FlashGameStatsRequest request) {
      return call("/GetFlashGameStats", request, dev.freggy.stats.service.Service.FlashStatisticCompound.class);
    }
  
    @Override
    public dev.freggy.stats.service.Service.FlashStatisticCompound getFlashStats(dev.freggy.stats.service.Service.FlashStatsCompoundRequest request) {
      return call("/GetFlashStats", request, dev.freggy.stats.service.Service.FlashStatisticCompound.class);
    }
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
