// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	fmt "fmt"
	model "freggy.dev/stats/rpc/go/model"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetFlashStatsResponse struct {
	Stats                *model.FlashStatisticCompound `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetFlashStatsResponse) Reset()         { *m = GetFlashStatsResponse{} }
func (m *GetFlashStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetFlashStatsResponse) ProtoMessage()    {}
func (*GetFlashStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *GetFlashStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlashStatsResponse.Unmarshal(m, b)
}
func (m *GetFlashStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlashStatsResponse.Marshal(b, m, deterministic)
}
func (m *GetFlashStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlashStatsResponse.Merge(m, src)
}
func (m *GetFlashStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetFlashStatsResponse.Size(m)
}
func (m *GetFlashStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlashStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlashStatsResponse proto.InternalMessageInfo

func (m *GetFlashStatsResponse) GetStats() *model.FlashStatisticCompound {
	if m != nil {
		return m.Stats
	}
	return nil
}

type GetFlashMapStatsRequest struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Maps                 []string `protobuf:"bytes,2,rep,name=maps,proto3" json:"maps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlashMapStatsRequest) Reset()         { *m = GetFlashMapStatsRequest{} }
func (m *GetFlashMapStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetFlashMapStatsRequest) ProtoMessage()    {}
func (*GetFlashMapStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *GetFlashMapStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlashMapStatsRequest.Unmarshal(m, b)
}
func (m *GetFlashMapStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlashMapStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetFlashMapStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlashMapStatsRequest.Merge(m, src)
}
func (m *GetFlashMapStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetFlashMapStatsRequest.Size(m)
}
func (m *GetFlashMapStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlashMapStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlashMapStatsRequest proto.InternalMessageInfo

func (m *GetFlashMapStatsRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *GetFlashMapStatsRequest) GetMaps() []string {
	if m != nil {
		return m.Maps
	}
	return nil
}

type GetFlashGameStatsRequest struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlashGameStatsRequest) Reset()         { *m = GetFlashGameStatsRequest{} }
func (m *GetFlashGameStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetFlashGameStatsRequest) ProtoMessage()    {}
func (*GetFlashGameStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *GetFlashGameStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlashGameStatsRequest.Unmarshal(m, b)
}
func (m *GetFlashGameStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlashGameStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetFlashGameStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlashGameStatsRequest.Merge(m, src)
}
func (m *GetFlashGameStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetFlashGameStatsRequest.Size(m)
}
func (m *GetFlashGameStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlashGameStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlashGameStatsRequest proto.InternalMessageInfo

func (m *GetFlashGameStatsRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

type GetFlashStatsCompoundRequest struct {
	PlayerId             string   `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Maps                 []string `protobuf:"bytes,2,rep,name=maps,proto3" json:"maps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlashStatsCompoundRequest) Reset()         { *m = GetFlashStatsCompoundRequest{} }
func (m *GetFlashStatsCompoundRequest) String() string { return proto.CompactTextString(m) }
func (*GetFlashStatsCompoundRequest) ProtoMessage()    {}
func (*GetFlashStatsCompoundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GetFlashStatsCompoundRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlashStatsCompoundRequest.Unmarshal(m, b)
}
func (m *GetFlashStatsCompoundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlashStatsCompoundRequest.Marshal(b, m, deterministic)
}
func (m *GetFlashStatsCompoundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlashStatsCompoundRequest.Merge(m, src)
}
func (m *GetFlashStatsCompoundRequest) XXX_Size() int {
	return xxx_messageInfo_GetFlashStatsCompoundRequest.Size(m)
}
func (m *GetFlashStatsCompoundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlashStatsCompoundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlashStatsCompoundRequest proto.InternalMessageInfo

func (m *GetFlashStatsCompoundRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *GetFlashStatsCompoundRequest) GetMaps() []string {
	if m != nil {
		return m.Maps
	}
	return nil
}

type UpdateFlashStatsRequest struct {
	PlayerId             string                        `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Stats                *model.FlashStatisticCompound `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *UpdateFlashStatsRequest) Reset()         { *m = UpdateFlashStatsRequest{} }
func (m *UpdateFlashStatsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFlashStatsRequest) ProtoMessage()    {}
func (*UpdateFlashStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *UpdateFlashStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFlashStatsRequest.Unmarshal(m, b)
}
func (m *UpdateFlashStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFlashStatsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFlashStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFlashStatsRequest.Merge(m, src)
}
func (m *UpdateFlashStatsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFlashStatsRequest.Size(m)
}
func (m *UpdateFlashStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFlashStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFlashStatsRequest proto.InternalMessageInfo

func (m *UpdateFlashStatsRequest) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *UpdateFlashStatsRequest) GetStats() *model.FlashStatisticCompound {
	if m != nil {
		return m.Stats
	}
	return nil
}

type UpdateFlashStatsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFlashStatsResponse) Reset()         { *m = UpdateFlashStatsResponse{} }
func (m *UpdateFlashStatsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFlashStatsResponse) ProtoMessage()    {}
func (*UpdateFlashStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *UpdateFlashStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFlashStatsResponse.Unmarshal(m, b)
}
func (m *UpdateFlashStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFlashStatsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFlashStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFlashStatsResponse.Merge(m, src)
}
func (m *UpdateFlashStatsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFlashStatsResponse.Size(m)
}
func (m *UpdateFlashStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFlashStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFlashStatsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetFlashStatsResponse)(nil), "service.GetFlashStatsResponse")
	proto.RegisterType((*GetFlashMapStatsRequest)(nil), "service.GetFlashMapStatsRequest")
	proto.RegisterType((*GetFlashGameStatsRequest)(nil), "service.GetFlashGameStatsRequest")
	proto.RegisterType((*GetFlashStatsCompoundRequest)(nil), "service.GetFlashStatsCompoundRequest")
	proto.RegisterType((*UpdateFlashStatsRequest)(nil), "service.UpdateFlashStatsRequest")
	proto.RegisterType((*UpdateFlashStatsResponse)(nil), "service.UpdateFlashStatsResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xdd, 0x4a, 0xc3, 0x30,
	0x14, 0xc7, 0xd9, 0xfc, 0xdc, 0xd1, 0xc1, 0x16, 0x90, 0x96, 0x22, 0xd2, 0x55, 0x84, 0xdd, 0x58,
	0x61, 0x82, 0x0f, 0xa0, 0xb0, 0xb1, 0x0b, 0xbd, 0xe8, 0xfc, 0x00, 0xef, 0xe2, 0x72, 0x36, 0x0b,
	0xed, 0x12, 0x9b, 0x6c, 0xb0, 0x87, 0xf6, 0x1d, 0x64, 0xcd, 0x52, 0xd6, 0xd6, 0xb9, 0xe2, 0x5d,
	0x73, 0x72, 0xce, 0xaf, 0xc9, 0xff, 0x47, 0xa0, 0x29, 0x31, 0x59, 0x84, 0x63, 0xf4, 0x45, 0xc2,
	0x15, 0x27, 0x47, 0xeb, 0xa5, 0xd3, 0x8e, 0x39, 0xc3, 0xe8, 0x66, 0x12, 0x51, 0xf9, 0xa9, 0xf7,
	0xbc, 0x3e, 0x9c, 0x0d, 0x50, 0xf5, 0x57, 0x95, 0x91, 0xa2, 0x4a, 0x06, 0x28, 0x05, 0x9f, 0x49,
	0x24, 0xd7, 0x70, 0x20, 0x57, 0x05, 0xbb, 0xe6, 0xd6, 0xba, 0x27, 0x3d, 0xcb, 0xcf, 0x7a, 0x42,
	0xa9, 0xc2, 0xf1, 0x03, 0x8f, 0x05, 0x9f, 0xcf, 0x58, 0xa0, 0xbb, 0xbc, 0x21, 0x58, 0x86, 0xf3,
	0x48, 0xc5, 0x1a, 0xf5, 0x35, 0x47, 0xa9, 0x88, 0x03, 0xc7, 0x22, 0xa2, 0x4b, 0x4c, 0x86, 0x2c,
	0x85, 0x35, 0x82, 0x6c, 0x4d, 0x08, 0xec, 0xc7, 0x54, 0x48, 0xbb, 0xee, 0xee, 0x75, 0x1b, 0x41,
	0xfa, 0xed, 0xdd, 0x81, 0x6d, 0x50, 0x03, 0x1a, 0x63, 0x55, 0x96, 0xf7, 0x04, 0xe7, 0xb9, 0xab,
	0x64, 0x47, 0xfc, 0xe7, 0x39, 0x18, 0x58, 0x2f, 0x82, 0x51, 0x85, 0x9b, 0xe9, 0xec, 0x46, 0x65,
	0xc1, 0xd5, 0x2b, 0x05, 0xe7, 0x80, 0x5d, 0xfe, 0x8b, 0x76, 0xd0, 0xfb, 0xae, 0xc3, 0x69, 0x5a,
	0x19, 0x69, 0x81, 0xe4, 0x19, 0x5a, 0xc5, 0x94, 0x89, 0xeb, 0x1b, 0xdb, 0x5b, 0x04, 0x38, 0x17,
	0xa5, 0x8e, 0xbc, 0xea, 0x57, 0x68, 0x97, 0x02, 0x27, 0x9d, 0xd2, 0x50, 0x51, 0x46, 0x05, 0x6e,
	0x33, 0xb7, 0x41, 0xae, 0x7e, 0x1f, 0x28, 0x88, 0xda, 0xc9, 0x7d, 0x83, 0x56, 0x31, 0xb2, 0x8d,
	0x14, 0xb6, 0x38, 0x73, 0x3a, 0x7f, 0x74, 0x68, 0xf0, 0xfd, 0x25, 0xd8, 0x0c, 0x17, 0xfe, 0x24,
	0xc1, 0xe9, 0x74, 0xe9, 0xa7, 0x7e, 0xcc, 0xd0, 0xbb, 0x79, 0x44, 0x1f, 0x87, 0xe9, 0xc3, 0xb9,
	0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x19, 0xde, 0x66, 0x65, 0x03, 0x00, 0x00,
}
