// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flash.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FlashStatisticCompound struct {
	GameSummary          *FlashGameStatistic  `protobuf:"bytes,1,opt,name=gameSummary,proto3" json:"gameSummary,omitempty"`
	MapSummary           []*FlashMapStatistic `protobuf:"bytes,2,rep,name=mapSummary,proto3" json:"mapSummary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FlashStatisticCompound) Reset()         { *m = FlashStatisticCompound{} }
func (m *FlashStatisticCompound) String() string { return proto.CompactTextString(m) }
func (*FlashStatisticCompound) ProtoMessage()    {}
func (*FlashStatisticCompound) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d8b97a8ce98af0, []int{0}
}

func (m *FlashStatisticCompound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlashStatisticCompound.Unmarshal(m, b)
}
func (m *FlashStatisticCompound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlashStatisticCompound.Marshal(b, m, deterministic)
}
func (m *FlashStatisticCompound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlashStatisticCompound.Merge(m, src)
}
func (m *FlashStatisticCompound) XXX_Size() int {
	return xxx_messageInfo_FlashStatisticCompound.Size(m)
}
func (m *FlashStatisticCompound) XXX_DiscardUnknown() {
	xxx_messageInfo_FlashStatisticCompound.DiscardUnknown(m)
}

var xxx_messageInfo_FlashStatisticCompound proto.InternalMessageInfo

func (m *FlashStatisticCompound) GetGameSummary() *FlashGameStatistic {
	if m != nil {
		return m.GameSummary
	}
	return nil
}

func (m *FlashStatisticCompound) GetMapSummary() []*FlashMapStatistic {
	if m != nil {
		return m.MapSummary
	}
	return nil
}

type FlashGameStatistic struct {
	Wins                 uint32   `protobuf:"varint,1,opt,name=wins,proto3" json:"wins,omitempty"`
	Deaths               uint32   `protobuf:"varint,2,opt,name=deaths,proto3" json:"deaths,omitempty"`
	GamesPlayed          uint32   `protobuf:"varint,3,opt,name=games_played,json=gamesPlayed,proto3" json:"games_played,omitempty"`
	InstantDeaths        uint32   `protobuf:"varint,4,opt,name=instant_deaths,json=instantDeaths,proto3" json:"instant_deaths,omitempty"`
	Checkpoints          uint32   `protobuf:"varint,5,opt,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlashGameStatistic) Reset()         { *m = FlashGameStatistic{} }
func (m *FlashGameStatistic) String() string { return proto.CompactTextString(m) }
func (*FlashGameStatistic) ProtoMessage()    {}
func (*FlashGameStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d8b97a8ce98af0, []int{1}
}

func (m *FlashGameStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlashGameStatistic.Unmarshal(m, b)
}
func (m *FlashGameStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlashGameStatistic.Marshal(b, m, deterministic)
}
func (m *FlashGameStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlashGameStatistic.Merge(m, src)
}
func (m *FlashGameStatistic) XXX_Size() int {
	return xxx_messageInfo_FlashGameStatistic.Size(m)
}
func (m *FlashGameStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_FlashGameStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_FlashGameStatistic proto.InternalMessageInfo

func (m *FlashGameStatistic) GetWins() uint32 {
	if m != nil {
		return m.Wins
	}
	return 0
}

func (m *FlashGameStatistic) GetDeaths() uint32 {
	if m != nil {
		return m.Deaths
	}
	return 0
}

func (m *FlashGameStatistic) GetGamesPlayed() uint32 {
	if m != nil {
		return m.GamesPlayed
	}
	return 0
}

func (m *FlashGameStatistic) GetInstantDeaths() uint32 {
	if m != nil {
		return m.InstantDeaths
	}
	return 0
}

func (m *FlashGameStatistic) GetCheckpoints() uint32 {
	if m != nil {
		return m.Checkpoints
	}
	return 0
}

type FlashMapStatistic struct {
	Name                 string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TimeNeeded           uint64                      `protobuf:"varint,2,opt,name=time_needed,json=timeNeeded,proto3" json:"time_needed,omitempty"`
	RecordTime           uint64                      `protobuf:"varint,3,opt,name=record_time,json=recordTime,proto3" json:"record_time,omitempty"`
	AccomplishedAt       string                      `protobuf:"bytes,4,opt,name=accomplished_at,json=accomplishedAt,proto3" json:"accomplished_at,omitempty"`
	Checkpoints          []*FlashCheckpointStatistic `protobuf:"bytes,5,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *FlashMapStatistic) Reset()         { *m = FlashMapStatistic{} }
func (m *FlashMapStatistic) String() string { return proto.CompactTextString(m) }
func (*FlashMapStatistic) ProtoMessage()    {}
func (*FlashMapStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d8b97a8ce98af0, []int{2}
}

func (m *FlashMapStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlashMapStatistic.Unmarshal(m, b)
}
func (m *FlashMapStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlashMapStatistic.Marshal(b, m, deterministic)
}
func (m *FlashMapStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlashMapStatistic.Merge(m, src)
}
func (m *FlashMapStatistic) XXX_Size() int {
	return xxx_messageInfo_FlashMapStatistic.Size(m)
}
func (m *FlashMapStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_FlashMapStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_FlashMapStatistic proto.InternalMessageInfo

func (m *FlashMapStatistic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FlashMapStatistic) GetTimeNeeded() uint64 {
	if m != nil {
		return m.TimeNeeded
	}
	return 0
}

func (m *FlashMapStatistic) GetRecordTime() uint64 {
	if m != nil {
		return m.RecordTime
	}
	return 0
}

func (m *FlashMapStatistic) GetAccomplishedAt() string {
	if m != nil {
		return m.AccomplishedAt
	}
	return ""
}

func (m *FlashMapStatistic) GetCheckpoints() []*FlashCheckpointStatistic {
	if m != nil {
		return m.Checkpoints
	}
	return nil
}

type FlashCheckpointStatistic struct {
	Checkpoint           int32    `protobuf:"fixed32,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	TimeNeeded           uint64   `protobuf:"varint,2,opt,name=time_needed,json=timeNeeded,proto3" json:"time_needed,omitempty"`
	AccomplishedAt       string   `protobuf:"bytes,3,opt,name=accomplished_at,json=accomplishedAt,proto3" json:"accomplished_at,omitempty"`
	RecordTime           uint64   `protobuf:"varint,4,opt,name=record_time,json=recordTime,proto3" json:"record_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlashCheckpointStatistic) Reset()         { *m = FlashCheckpointStatistic{} }
func (m *FlashCheckpointStatistic) String() string { return proto.CompactTextString(m) }
func (*FlashCheckpointStatistic) ProtoMessage()    {}
func (*FlashCheckpointStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d8b97a8ce98af0, []int{3}
}

func (m *FlashCheckpointStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlashCheckpointStatistic.Unmarshal(m, b)
}
func (m *FlashCheckpointStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlashCheckpointStatistic.Marshal(b, m, deterministic)
}
func (m *FlashCheckpointStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlashCheckpointStatistic.Merge(m, src)
}
func (m *FlashCheckpointStatistic) XXX_Size() int {
	return xxx_messageInfo_FlashCheckpointStatistic.Size(m)
}
func (m *FlashCheckpointStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_FlashCheckpointStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_FlashCheckpointStatistic proto.InternalMessageInfo

func (m *FlashCheckpointStatistic) GetCheckpoint() int32 {
	if m != nil {
		return m.Checkpoint
	}
	return 0
}

func (m *FlashCheckpointStatistic) GetTimeNeeded() uint64 {
	if m != nil {
		return m.TimeNeeded
	}
	return 0
}

func (m *FlashCheckpointStatistic) GetAccomplishedAt() string {
	if m != nil {
		return m.AccomplishedAt
	}
	return ""
}

func (m *FlashCheckpointStatistic) GetRecordTime() uint64 {
	if m != nil {
		return m.RecordTime
	}
	return 0
}

func init() {
	proto.RegisterType((*FlashStatisticCompound)(nil), "FlashStatisticCompound")
	proto.RegisterType((*FlashGameStatistic)(nil), "FlashGameStatistic")
	proto.RegisterType((*FlashMapStatistic)(nil), "FlashMapStatistic")
	proto.RegisterType((*FlashCheckpointStatistic)(nil), "FlashCheckpointStatistic")
}

func init() { proto.RegisterFile("flash.proto", fileDescriptor_83d8b97a8ce98af0) }

var fileDescriptor_83d8b97a8ce98af0 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4e, 0xfa, 0x40,
	0x10, 0xc6, 0x53, 0x28, 0x24, 0x4c, 0xff, 0x40, 0xfe, 0x6b, 0x42, 0xea, 0x45, 0x90, 0xc4, 0xc8,
	0xa9, 0x07, 0x8c, 0x27, 0x4f, 0x8a, 0xd1, 0x93, 0xc6, 0x14, 0x4f, 0x5e, 0x9a, 0xb5, 0xbb, 0xd0,
	0x8d, 0xdd, 0x6e, 0xd3, 0x5d, 0x34, 0x9c, 0x7d, 0x16, 0x6f, 0xbe, 0x8b, 0xaf, 0x64, 0x76, 0x0a,
	0xd2, 0x00, 0xc6, 0x53, 0x77, 0x7f, 0xf3, 0xcd, 0xf4, 0xfb, 0xa6, 0x05, 0x6f, 0x96, 0x52, 0x9d,
	0x04, 0x79, 0xa1, 0x8c, 0x1a, 0xbe, 0x3b, 0xd0, 0xbb, 0xb1, 0xf7, 0xa9, 0xa1, 0x46, 0x68, 0x23,
	0xe2, 0x89, 0x92, 0xb9, 0x5a, 0x64, 0x8c, 0x9c, 0x83, 0x37, 0xa7, 0x92, 0x4f, 0x17, 0x52, 0xd2,
	0x62, 0xe9, 0x3b, 0x03, 0x67, 0xe4, 0x8d, 0x0f, 0x02, 0x54, 0xdf, 0xda, 0xc2, 0xba, 0x23, 0xac,
	0xea, 0xc8, 0x18, 0x40, 0xd2, 0x7c, 0xdd, 0x55, 0x1b, 0xd4, 0x47, 0xde, 0x98, 0x94, 0x5d, 0x77,
	0x34, 0xdf, 0x34, 0x55, 0x54, 0xc3, 0x4f, 0x07, 0xc8, 0xee, 0x5c, 0x42, 0xc0, 0x7d, 0x13, 0x99,
	0xc6, 0x57, 0xb7, 0x43, 0x3c, 0x93, 0x1e, 0x34, 0x19, 0xa7, 0x26, 0xd1, 0x7e, 0x0d, 0xe9, 0xea,
	0x46, 0x8e, 0xe1, 0x9f, 0x75, 0xa1, 0xa3, 0x3c, 0xa5, 0x4b, 0xce, 0xfc, 0x3a, 0x56, 0xd1, 0x99,
	0x7e, 0x40, 0x44, 0x4e, 0xa0, 0x23, 0x32, 0x6d, 0x68, 0x66, 0xa2, 0xd5, 0x08, 0x17, 0x45, 0xed,
	0x15, 0xbd, 0x2e, 0x27, 0x0d, 0xc0, 0x8b, 0x13, 0x1e, 0xbf, 0xe4, 0x4a, 0x64, 0x46, 0xfb, 0x8d,
	0x72, 0x50, 0x05, 0x0d, 0xbf, 0x1c, 0xf8, 0xbf, 0x13, 0xc8, 0xba, 0xcd, 0xa8, 0xe4, 0xe8, 0xb6,
	0x15, 0xe2, 0x99, 0xf4, 0xc1, 0x33, 0x42, 0xf2, 0x28, 0xe3, 0x9c, 0x71, 0x86, 0x96, 0xdd, 0x10,
	0x2c, 0xba, 0x47, 0x62, 0x05, 0x05, 0x8f, 0x55, 0xc1, 0x22, 0x0b, 0xd1, 0xb5, 0x1b, 0x42, 0x89,
	0x1e, 0x85, 0xe4, 0xe4, 0x14, 0xba, 0x34, 0x8e, 0x95, 0xcc, 0x53, 0xa1, 0x13, 0xce, 0x22, 0x6a,
	0xd0, 0x75, 0x2b, 0xec, 0x54, 0xf1, 0xa5, 0x21, 0x17, 0xdb, 0xb6, 0xed, 0xe2, 0x0f, 0xcb, 0xc5,
	0x4f, 0x7e, 0x0a, 0x95, 0x8f, 0x56, 0x4d, 0xf4, 0xe1, 0x80, 0xff, 0x9b, 0x92, 0x1c, 0x01, 0x6c,
	0xb4, 0x18, 0xaf, 0x1b, 0x56, 0xc8, 0xdf, 0x21, 0xf7, 0x64, 0xa8, 0xef, 0xcd, 0xb0, 0xb5, 0x0d,
	0x77, 0x7b, 0x1b, 0x57, 0x7d, 0xe8, 0x31, 0xfe, 0x1a, 0xcc, 0x0a, 0x3e, 0x9f, 0x2f, 0x03, 0x6d,
	0xa8, 0xd1, 0x81, 0x54, 0x8c, 0xa7, 0x4f, 0x0d, 0x7c, 0x3c, 0x37, 0xf1, 0xb7, 0x3e, 0xfb, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x64, 0xfc, 0xd9, 0x67, 0xe5, 0x02, 0x00, 0x00,
}
