// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flash.proto

package v1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FlashMapStatisticCollection struct {
	PlayerId             string               `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Maps                 []*FlashMapStatistic `protobuf:"bytes,2,rep,name=maps,proto3" json:"maps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FlashMapStatisticCollection) Reset()         { *m = FlashMapStatisticCollection{} }
func (m *FlashMapStatisticCollection) String() string { return proto.CompactTextString(m) }
func (*FlashMapStatisticCollection) ProtoMessage()    {}
func (*FlashMapStatisticCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d8b97a8ce98af0, []int{0}
}

func (m *FlashMapStatisticCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlashMapStatisticCollection.Unmarshal(m, b)
}
func (m *FlashMapStatisticCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlashMapStatisticCollection.Marshal(b, m, deterministic)
}
func (m *FlashMapStatisticCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlashMapStatisticCollection.Merge(m, src)
}
func (m *FlashMapStatisticCollection) XXX_Size() int {
	return xxx_messageInfo_FlashMapStatisticCollection.Size(m)
}
func (m *FlashMapStatisticCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_FlashMapStatisticCollection.DiscardUnknown(m)
}

var xxx_messageInfo_FlashMapStatisticCollection proto.InternalMessageInfo

func (m *FlashMapStatisticCollection) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *FlashMapStatisticCollection) GetMaps() []*FlashMapStatistic {
	if m != nil {
		return m.Maps
	}
	return nil
}

type FlashAllStatistics struct {
	PlayerId             string                `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerStats          *FlashPlayerStatistic `protobuf:"bytes,2,opt,name=playerStats,proto3" json:"playerStats,omitempty"`
	MapStats             []*FlashMapStatistic  `protobuf:"bytes,3,rep,name=mapStats,proto3" json:"mapStats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FlashAllStatistics) Reset()         { *m = FlashAllStatistics{} }
func (m *FlashAllStatistics) String() string { return proto.CompactTextString(m) }
func (*FlashAllStatistics) ProtoMessage()    {}
func (*FlashAllStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d8b97a8ce98af0, []int{1}
}

func (m *FlashAllStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlashAllStatistics.Unmarshal(m, b)
}
func (m *FlashAllStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlashAllStatistics.Marshal(b, m, deterministic)
}
func (m *FlashAllStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlashAllStatistics.Merge(m, src)
}
func (m *FlashAllStatistics) XXX_Size() int {
	return xxx_messageInfo_FlashAllStatistics.Size(m)
}
func (m *FlashAllStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_FlashAllStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_FlashAllStatistics proto.InternalMessageInfo

func (m *FlashAllStatistics) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *FlashAllStatistics) GetPlayerStats() *FlashPlayerStatistic {
	if m != nil {
		return m.PlayerStats
	}
	return nil
}

func (m *FlashAllStatistics) GetMapStats() []*FlashMapStatistic {
	if m != nil {
		return m.MapStats
	}
	return nil
}

type FlashPlayerStatistic struct {
	Wins                 uint32   `protobuf:"varint,1,opt,name=wins,proto3" json:"wins,omitempty"`
	Deaths               uint32   `protobuf:"varint,2,opt,name=deaths,proto3" json:"deaths,omitempty"`
	GamesPlayed          uint32   `protobuf:"varint,3,opt,name=games_played,json=gamesPlayed,proto3" json:"games_played,omitempty"`
	InstantDeaths        uint32   `protobuf:"varint,4,opt,name=instant_deaths,json=instantDeaths,proto3" json:"instant_deaths,omitempty"`
	Checkpoints          uint32   `protobuf:"varint,5,opt,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	Points               uint32   `protobuf:"varint,6,opt,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlashPlayerStatistic) Reset()         { *m = FlashPlayerStatistic{} }
func (m *FlashPlayerStatistic) String() string { return proto.CompactTextString(m) }
func (*FlashPlayerStatistic) ProtoMessage()    {}
func (*FlashPlayerStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d8b97a8ce98af0, []int{2}
}

func (m *FlashPlayerStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlashPlayerStatistic.Unmarshal(m, b)
}
func (m *FlashPlayerStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlashPlayerStatistic.Marshal(b, m, deterministic)
}
func (m *FlashPlayerStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlashPlayerStatistic.Merge(m, src)
}
func (m *FlashPlayerStatistic) XXX_Size() int {
	return xxx_messageInfo_FlashPlayerStatistic.Size(m)
}
func (m *FlashPlayerStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_FlashPlayerStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_FlashPlayerStatistic proto.InternalMessageInfo

func (m *FlashPlayerStatistic) GetWins() uint32 {
	if m != nil {
		return m.Wins
	}
	return 0
}

func (m *FlashPlayerStatistic) GetDeaths() uint32 {
	if m != nil {
		return m.Deaths
	}
	return 0
}

func (m *FlashPlayerStatistic) GetGamesPlayed() uint32 {
	if m != nil {
		return m.GamesPlayed
	}
	return 0
}

func (m *FlashPlayerStatistic) GetInstantDeaths() uint32 {
	if m != nil {
		return m.InstantDeaths
	}
	return 0
}

func (m *FlashPlayerStatistic) GetCheckpoints() uint32 {
	if m != nil {
		return m.Checkpoints
	}
	return 0
}

func (m *FlashPlayerStatistic) GetPoints() uint32 {
	if m != nil {
		return m.Points
	}
	return 0
}

type FlashMapStatistic struct {
	Name                 string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TimeNeeded           uint64                      `protobuf:"varint,2,opt,name=time_needed,json=timeNeeded,proto3" json:"time_needed,omitempty"`
	AccomplishedAt       string                      `protobuf:"bytes,3,opt,name=accomplished_at,json=accomplishedAt,proto3" json:"accomplished_at,omitempty"`
	Checkpoints          []*FlashCheckpointStatistic `protobuf:"bytes,4,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *FlashMapStatistic) Reset()         { *m = FlashMapStatistic{} }
func (m *FlashMapStatistic) String() string { return proto.CompactTextString(m) }
func (*FlashMapStatistic) ProtoMessage()    {}
func (*FlashMapStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d8b97a8ce98af0, []int{3}
}

func (m *FlashMapStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlashMapStatistic.Unmarshal(m, b)
}
func (m *FlashMapStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlashMapStatistic.Marshal(b, m, deterministic)
}
func (m *FlashMapStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlashMapStatistic.Merge(m, src)
}
func (m *FlashMapStatistic) XXX_Size() int {
	return xxx_messageInfo_FlashMapStatistic.Size(m)
}
func (m *FlashMapStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_FlashMapStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_FlashMapStatistic proto.InternalMessageInfo

func (m *FlashMapStatistic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FlashMapStatistic) GetTimeNeeded() uint64 {
	if m != nil {
		return m.TimeNeeded
	}
	return 0
}

func (m *FlashMapStatistic) GetAccomplishedAt() string {
	if m != nil {
		return m.AccomplishedAt
	}
	return ""
}

func (m *FlashMapStatistic) GetCheckpoints() []*FlashCheckpointStatistic {
	if m != nil {
		return m.Checkpoints
	}
	return nil
}

type FlashCheckpointStatistic struct {
	Checkpoint           int32    `protobuf:"fixed32,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	TimeNeeded           uint64   `protobuf:"varint,2,opt,name=time_needed,json=timeNeeded,proto3" json:"time_needed,omitempty"`
	AccomplishedAt       string   `protobuf:"bytes,3,opt,name=accomplished_at,json=accomplishedAt,proto3" json:"accomplished_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlashCheckpointStatistic) Reset()         { *m = FlashCheckpointStatistic{} }
func (m *FlashCheckpointStatistic) String() string { return proto.CompactTextString(m) }
func (*FlashCheckpointStatistic) ProtoMessage()    {}
func (*FlashCheckpointStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_83d8b97a8ce98af0, []int{4}
}

func (m *FlashCheckpointStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlashCheckpointStatistic.Unmarshal(m, b)
}
func (m *FlashCheckpointStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlashCheckpointStatistic.Marshal(b, m, deterministic)
}
func (m *FlashCheckpointStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlashCheckpointStatistic.Merge(m, src)
}
func (m *FlashCheckpointStatistic) XXX_Size() int {
	return xxx_messageInfo_FlashCheckpointStatistic.Size(m)
}
func (m *FlashCheckpointStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_FlashCheckpointStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_FlashCheckpointStatistic proto.InternalMessageInfo

func (m *FlashCheckpointStatistic) GetCheckpoint() int32 {
	if m != nil {
		return m.Checkpoint
	}
	return 0
}

func (m *FlashCheckpointStatistic) GetTimeNeeded() uint64 {
	if m != nil {
		return m.TimeNeeded
	}
	return 0
}

func (m *FlashCheckpointStatistic) GetAccomplishedAt() string {
	if m != nil {
		return m.AccomplishedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*FlashMapStatisticCollection)(nil), "stats.v1.FlashMapStatisticCollection")
	proto.RegisterType((*FlashAllStatistics)(nil), "stats.v1.FlashAllStatistics")
	proto.RegisterType((*FlashPlayerStatistic)(nil), "stats.v1.FlashPlayerStatistic")
	proto.RegisterType((*FlashMapStatistic)(nil), "stats.v1.FlashMapStatistic")
	proto.RegisterType((*FlashCheckpointStatistic)(nil), "stats.v1.FlashCheckpointStatistic")
}

func init() {
	proto.RegisterFile("flash.proto", fileDescriptor_83d8b97a8ce98af0)
}

var fileDescriptor_83d8b97a8ce98af0 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x6d, 0x2c, 0xed, 0xc4, 0xb6, 0xb8, 0x88, 0x04, 0x0b, 0xb5, 0x06, 0xc4, 0x9e, 0x22,
	0xad, 0x07, 0xaf, 0xd6, 0x16, 0xc1, 0x83, 0x22, 0xf1, 0xe6, 0x25, 0xac, 0xc9, 0x6a, 0x56, 0x93,
	0x4d, 0xe8, 0x2e, 0x15, 0xef, 0xfe, 0x1b, 0x7f, 0x80, 0xff, 0xc0, 0xdf, 0x25, 0x99, 0x8d, 0x31,
	0xb6, 0x7e, 0x5c, 0xbc, 0xcd, 0xbc, 0x79, 0xfb, 0xe6, 0xbd, 0x09, 0x01, 0xeb, 0x36, 0xa6, 0x32,
	0x72, 0xb3, 0x79, 0xaa, 0x52, 0xd2, 0x94, 0x8a, 0x2a, 0xe9, 0x2e, 0x46, 0xce, 0x3d, 0xf4, 0x4e,
	0xf3, 0xc1, 0x39, 0xcd, 0xae, 0x14, 0x55, 0x5c, 0x2a, 0x1e, 0x4c, 0xd3, 0x38, 0x66, 0x81, 0xe2,
	0xa9, 0x20, 0xdb, 0xd0, 0xcc, 0x62, 0xfa, 0xc4, 0xe6, 0x67, 0xa1, 0x6d, 0x0c, 0x8c, 0x61, 0xcb,
	0x2b, 0x7b, 0x72, 0x00, 0x66, 0x42, 0x33, 0x69, 0xd7, 0x06, 0xf5, 0xa1, 0x35, 0xee, 0xb9, 0x1f,
	0x9a, 0xee, 0x8a, 0xa0, 0x87, 0x44, 0xe7, 0xc5, 0x00, 0x82, 0xb3, 0x49, 0x1c, 0x97, 0x33, 0xf9,
	0xeb, 0x8e, 0x63, 0xb0, 0x74, 0x9d, 0xf3, 0xf3, 0x55, 0xc6, 0xd0, 0x1a, 0xf7, 0x97, 0x56, 0x5d,
	0x96, 0x0c, 0xbd, 0xad, 0xfa, 0x84, 0x1c, 0x41, 0x33, 0xd1, 0x56, 0xa4, 0x5d, 0xff, 0xdb, 0x69,
	0x49, 0x76, 0xde, 0x0c, 0xd8, 0xfc, 0x4e, 0x9e, 0x10, 0x30, 0x1f, 0xb9, 0x90, 0xe8, 0xb5, 0xed,
	0x61, 0x4d, 0xb6, 0xa0, 0x11, 0x32, 0xaa, 0x22, 0x6d, 0xb1, 0xed, 0x15, 0x1d, 0xd9, 0x85, 0xf5,
	0x3b, 0x9a, 0x30, 0xe9, 0xa3, 0xa5, 0xd0, 0xae, 0xe3, 0xd4, 0x42, 0x0c, 0x75, 0x43, 0xb2, 0x07,
	0x1d, 0x2e, 0xa4, 0xa2, 0x42, 0xf9, 0x85, 0x84, 0x89, 0xa4, 0x76, 0x81, 0xce, 0xb4, 0xd2, 0x00,
	0xac, 0x20, 0x62, 0xc1, 0x43, 0x96, 0x72, 0xa1, 0xa4, 0xbd, 0xa6, 0x85, 0x2a, 0x50, 0xee, 0xa1,
	0x18, 0x36, 0xb4, 0x07, 0xdd, 0x39, 0xaf, 0x06, 0x6c, 0xac, 0x04, 0xcd, 0x53, 0x08, 0x9a, 0xb0,
	0xe2, 0xe2, 0x58, 0x93, 0x1d, 0xb0, 0x14, 0x4f, 0x98, 0x2f, 0x18, 0x0b, 0x59, 0x88, 0x51, 0x4c,
	0x0f, 0x72, 0xe8, 0x02, 0x11, 0xb2, 0x0f, 0x5d, 0x1a, 0x04, 0x69, 0x92, 0xc5, 0x5c, 0x46, 0x2c,
	0xf4, 0xa9, 0xc2, 0x44, 0x2d, 0xaf, 0x53, 0x85, 0x27, 0x8a, 0xcc, 0xbe, 0xba, 0x35, 0xf1, 0xf0,
	0xce, 0xd2, 0xe1, 0xa7, 0x25, 0xa3, 0xf2, 0xed, 0x2a, 0xcf, 0x9c, 0x67, 0x03, 0xec, 0x9f, 0x98,
	0xa4, 0x0f, 0xf0, 0xc9, 0xc5, 0x18, 0x5d, 0xaf, 0x82, 0xfc, 0x5f, 0x98, 0x13, 0xf3, 0xba, 0xb6,
	0x18, 0xdd, 0x34, 0xf0, 0xd7, 0x39, 0x7c, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x4c, 0x93, 0x9c,
	0x49, 0x03, 0x00, 0x00,
}
